apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-static-ebs-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # storageClassName: my-ebs-sc
  awsElasticBlockStore:
    volumeID: vol-0dce8336733c567c5
    fsType: ext4
